// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvaluatePro.Migrations
{
    [DbContext(typeof(EvaluateProDbContext))]
    partial class EvaluateProDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Criteria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Criteria1")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<int?>("Employeeid")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsManager")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LName")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Employeeid");

                    b.ToTable("Criterias");
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Fname")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsMAnager")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Lname")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Criteria", b =>
                {
                    b.HasOne("Employee", null)
                        .WithMany("Criteria")
                        .HasForeignKey("Employeeid");
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.Navigation("Criteria");
                });
#pragma warning restore 612, 618
        }
    }
}
